[build.environment]
PYTHON_VERSION = "3.11.5"  # Or another valid version

[build]
  functions = "functions"
  publish = "static"
  command = "pip install -r requirements.txt"

[functions]
  directory = "functions"
[build]
  publish = "build" # or "dist" if using a framework
  command = "npm run build" # or your specific build command
